before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: yXQTbGCBAOJziC37/8N/bX51Y8jK5aFy9Dl1b/cExJ8y+G9ZmiGdIzkwOOgIs8rJlsY1MFRfZo5DwTnw5pruGrubgCsmPKDerr52gD6T4eFaItoYkSMKZO5TT7anikwMHmBdDwPJzm1rW+39/aIYpcrc8Wch9r2s7DYxlnJlzFyAZxreZ82jSZL4ppja9Fc+VJ+nCmJ0yv7oMon6tka6kRwkipJfuUcDi5EoKZkAPcyn/GSKw3M8/J4LhL0/wC4EFNQNKT/feZq4MqQfKBI0qRxdxEujC1SO7bmiwGe2gVG+o5k+jPOCklIB93osh4v4KaDG8pPKgUDdsMMtpS/MSYIM4iUvj+A/FTJza4CdrEqjJzdSWtIp/afBt2F/8S+ae0/crcA2VqRkixrOZcHBVdTj9INpqsN26Lnj4Ul7f5gQ4H5LtvLX3DmfmRn0DzsWiikkJhmk2tumFyn1g5yVWaHatOcNED6AEixYLTPsPq45D7b+HuwYZMzF49L+Qb55XounTtV4WPxKbH7ltt7mqLJgFX+5H9RMhg8a4og4LSs2uFFfzbSYct9/DJS7fVjsmegDDe+QZa0mW63wWqfB14QA6KTMN999G1ByAs3TBlijP0lCXhlIWcXnq3qu5JT6LblXJgOR0rbh4y75xIFii4I0M8C9IEjhsHNyAhO+XqQ= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
